[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_zk_verifier = "BAeZT7LE3cdUkKR5e6EoDRvQQDER1xHXwRum5io2gJ93"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
