[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_zk_verifier = "AR9BVLEzUAUHK7Fq4SjXoRkE7mCSR2qnZHQDUCkUYruQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
