[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_zk_verifier = "5STsA74ZCLZXGdv33vP5fk1EgLBE4HNR494UpiqXXDz"

[programs.devnet]
solana_zk_verifier = "5STsA74ZCLZXGdv33vP5fk1EgLBE4HNR494UpiqXXDz"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
